name = "tropos"
description = "Configuration file reader/writer"
version = "0.1.0-dev"
licenses= "GPL-3.0-or-later"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]
tags = ["utility", "config", "json", "xml"]

website = "https://github.com/blancolioni/tropos"

