name = "tropos"
description = "Configuration file reader/writer"
version = "0.1.0-dev"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]
[[depends-on]]
wl_lib = "~0.1.0-dev"
